CREATE TABLE customers(
customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR2(50) NOT NULL,
email VARCHAR2(100) UNIQUE,
phone VARCHAR2(15),
address VARCHAR2(100),
created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE accounts(
account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id NUMBER,
account_type VARCHAR2(20),
balance NUMBER(12,2) DEFAULT 0,
status VARCHAR2(20) DEFAULT 'ACTIVE', -- ACTIVE / INACTIVE / CLOSED
created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
FOREIGN KEY(customer_id)
REFERENCES customers(customer_id)
);
CREATE TABLE transactions(
transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
account_id NUMBER,
transaction_type VARCHAR2(20),
amount NUMBER(12,2),
description VARCHAR2(100),
transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP,
FOREIGN KEY(account_id)
REFERENCES accounts(account_id)
);

CREATE TABLE loans(
loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id NUMBER,
loan_type VARCHAR2(50),
loan_amount NUMBER(12,2),
interest_rate NUMBER(5,2),
emi_amount NUMBER(12,2),
remaining_amount NUMBER(12,2),
payment_type VARCHAR2(20), -- MONTHLY / QUARTERLY / YEARLY
loan_status VARCHAR2(20) DEFAULT 'ACTIVE',
loan_date TIMESTAMP DEFAULT SYSTIMESTAMP,
FOREIGN KEY(customer_id) REFERENCES customers(customer_id)
);
